[project]
name = "neo-human-detector-batch"
version = "0.1.0"
requires-python = ">=3.10,<3.11"
dependencies = [
    "colorlog>=6.10.1",
    "fastapi>=0.124.4",
    "gdown>=5.2.2",
    "lapx>=0.9.4",
    "opencv-python",
    "pyserial>=3.5",
    "pytz>=2026.2",
    "tensorboard>=2.14.0",
    "torchreid>=0.2.5",
    "ultralytics>=8.4.60",
    "unidecode>=1.4.0",
    "uvicorn[standard]>=0.33.0",
    "yt-dlp>=2024.10.22",
]

[dependency-groups]
dev = [
    "ruff>=0.15.14",
]

[tool.uv.sources]
opencv-python = { path = "../../python-wheels/opencv/opencv_python-4.13.0.92-cp310-cp310-linux_x86_64.whl" }
