auto_start: false
detection:
  task: pose
  model_size: medium
  batch_size: 2
  conf: 0.47
  verbose: false
zone_state_machine:
  confirm_enter_time: 6.0
  confirm_exit_time: 6.0
  pending_enter_miss_grace_time: 1.5
reid:
  enabled: true
  zone_only: true
  require_occupied_zone: true
  model_path: weights/reid/osnet_ain_ms_d_c.pth.tar
  device: auto
  embedding:
    batch_size: 1
  track:
    buffer_min: 30
    grace_period: 90
    update_interval: 120
    max_buffer_size: 1
    gallery_cleanup_interval: 1800
    max_reverify_misses: 5
  quality:
    overlap_iou_threshold: 0.25
    overlap_ioa_threshold: 0.45
    stable_bbox_window: 30
    stable_center_shift_ratio: 0.2
    stable_size_change_ratio: 0.25
    laplacian_var_threshold: 50.0
  gallery:
    sim_threshold_match: 0.75
    ema_alpha: 0.75
    max_samples: 5
    ttl_minutes: 2.0
uart:
  port: /dev/ttyUSB0
  baudrate: 115200
cameras:
- name: AI Center
  stream:
    source: rtsp://admin:061223%40bC@192.168.0.10:554/Streaming/Channels/101
    protocol: tcp
    on_demand: true
  enabled: true
  zones:
  - id: 8xcdb
    name: nnq
    goal_pose:
      x: 0.0
      y: 0.0
      theta: 0.0
    points:
    - [418, 802]
    - [763, 757]
    - [819, 1080]
    - [439, 1080]
  - id: sfats
    name: Khách
    goal_pose:
      x: 0.0
      y: 0.0
      theta: 0.0
    points:
    - [1483, 354]
    - [1584, 443]
    - [1485, 529]
    - [1373, 419]
  id: gcphg
- name: Android Center
  stream:
    source: rtsp://admin:061223%40bC@192.168.0.15:554/Streaming/Channels/101
    protocol: tcp
    on_demand: true
  enabled: true
  zones:
  - id: l5t3k
    name: Khải
    goal_pose:
      x: 0.0
      y: 0.0
      theta: 0.0
    points:
    - [1131, 490]
    - [1578, 432]
    - [1552, 812]
    - [1126, 845]
  id: rtdll
