detector:
  source: rtsp://admin:phenikaaneo%40@192.168.0.150:554/Streaming/Channels/101
  model_path: weights/head/yolo8n_rknn_model
  conf: 0.4
  zone_check_mode: center
  confirm_enter_time: 5.5
  confirm_exit_time: 5.0
  pending_enter_miss_grace_time: 2.0
  vid_stride: 1
  verbose: false
  show: true
  show_scale: 0.55
uart:
  port: /dev/ttyS4
  baudrate: 115200
zones:
- name: diem_tiep_khach1
  goal_pose:
    x: -4.354399
    y: -1.9824829
    theta: 1.2466646
  points:
  - [685, 264]
  - [940, 225]
  - [990, 443]
  - [736, 501]
- name: zone_2
  goal_pose:
    x: -3.7456307
    y: -0.34589595
    theta: 2.0059733
  points:
  - [1216, 194]
  - [1543, 281]
  - [1472, 497]
  - [1140, 389]
