detector:
  source: rtsp://admin:phenikaaneo%40@192.168.0.150:554/Streaming/Channels/101
  model_path: weights/head/yolo8n_rknn_model
  conf: 0.5
  zone_check_mode: center
  confirm_enter_time: 5.3
  confirm_exit_time: 5.3
  pending_enter_miss_grace_time: 1.3
  vid_stride: 1
  verbose: false
  show: true
  show_scale: 0.55
uart:
  port: /dev/ttyS4
  baudrate: 115200
zones:
- name: diem_tiep_khach1
  goal_pose:
    x: -4.349722
    y: -1.7225691
    theta: 0.87882423
  points:
  - [921, 302]
  - [1199, 314]
  - [1218, 526]
  - [931, 520]
